'use strict';
const dates=[{value:'2026-10-02',day:'Пятница',num:'2'},{value:'2026-10-04',day:'Воскресенье',num:'4'},{value:'2026-10-05',day:'Понедельник',num:'5'}];
const cuisines=[['🍝','Итальянская'],['🍣','Японская'],['🥟','Грузинская'],['🥗','Европейская'],['🍔','Бургеры'],['✨','Доверюсь тебе']];
const times=['15:00','16:00','17:00','18:00','19:00','20:00'];
const state={step:0,date:'',cuisine:'',time:'',sending:false,sent:false};
const container=document.querySelector('#stepContent'),next=document.querySelector('#next'),back=document.querySelector('#back'),status=document.querySelector('#status');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dateLabel(){const d=dates.find(x=>x.value===state.date);return d?`${d.num} октября 2026, ${d.day.toLowerCase()}`:''}
function validStep(n){return n===0?dates.some(x=>x.value===state.date):n===1?cuisines.some(x=>x[1]===state.cuisine):/^([01]\d|2[0-3]):[0-5]\d$/.test(state.time)}
function choice(name,value,body,cl){return `<label class="choice"><input type="radio" name="${name}" value="${escapeHtml(value)}" ${state[name]===value?'checked':''}><span class="tile ${cl}">${body}</span></label>`}
function summary(){return `<div class="summary"><div><span>Когда</span><strong>${dates.find(x=>x.value===state.date)?.num} октября</strong></div><div><span>Кухня</span><strong>${escapeHtml(state.cuisine)}</strong></div><div><span>Во сколько</span><strong>${escapeHtml(state.time)}</strong></div></div>`}
function render(focus=false){status.textContent='';document.querySelector('#fallback').hidden=true;back.hidden=state.step===0||state.sent;next.hidden=state.sent;document.querySelectorAll('[data-step]').forEach(b=>{let n=Number(b.dataset.step);b.disabled=state.sending||state.sent||Array.from({length:n},(_,i)=>validStep(i)).includes(false);b.classList.toggle('current',n===state.step);if(n===state.step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});
let html='';
if(state.sent){html=`<div class="step success"><div class="success-mark">♡</div><h2>У нас будет<br>красивый вечер.</h2><p>Твой выбор принят сервисом отправки.<br>Артём, теперь всё за тобой!</p>${summary()}</div>`;container.innerHTML=html;return}
if(state.step===0)html=`<div class="step-head"><h2 tabindex="-1">Когда увидимся?</h2><span class="hint">Октябрь · 2026</span></div><fieldset class="dates"><legend>Выбери дату</legend>${dates.map(d=>choice('date',d.value,`<span class="day">${d.day}</span><strong>${d.num}</strong><span class="month">октября</span>`,'date-tile')).join('')}</fieldset><p class="selection-note">Выбери день, который хочется оставить для нас.</p>`;
if(state.step===1)html=`<div class="step-head"><h2 tabindex="-1">На что настроена?</h2><span class="hint">Дело вкуса</span></div><fieldset class="food-grid"><legend>Выбери кухню</legend>${cuisines.map(([icon,c])=>choice('cuisine',c,`<span class="food-icon" aria-hidden="true">${icon}</span><span>${c}</span>`,'food-tile')).join('')}</fieldset>`;
if(state.step===2)html=`<div class="step-head"><h2 tabindex="-1">Во сколько встретимся?</h2><span class="hint">По Москве</span></div><fieldset class="time-grid"><legend>Выбери время</legend>${times.map(t=>choice('time',t,t,'time-tile')).join('')}</fieldset><label class="custom-time">Или своё время<input aria-label="Своё время встречи" type="time" id="customTime" value="${state.time&&!times.includes(state.time)?state.time:''}"></label>`;
if(state.step===3)html=`<div class="step-head"><h2 tabindex="-1">Значит, договорились?</h2><span class="hint">Наш маленький план</span></div>${summary()}<p class="send-note">Отправь свой выбор Артёму — остальное он возьмёт на себя.</p>`;
container.innerHTML=`<div class="step">${html}</div>`;next.innerHTML=[`Выбрать кухню <span>↗</span>`,`Выбрать время <span>↗</span>`,`Посмотреть наш план <span>↗</span>`,`Да, идём на свидание <span>♡</span>`][state.step];next.disabled=state.step<3?!validStep(state.step):![0,1,2].every(validStep);if(focus)container.querySelector('h2')?.focus({preventScroll:true});}
container.addEventListener('change',e=>{if(state.sending)return;if(e.target.type==='radio'){state[e.target.name]=e.target.value;if(e.target.name==='time')document.querySelector('#customTime').value='';next.disabled=!validStep(state.step)}if(e.target.id==='customTime'){state.time=e.target.value;container.querySelectorAll('[name="time"]').forEach(r=>r.checked=r.value===state.time);next.disabled=!validStep(2)}});
back.addEventListener('click',()=>{if(!state.sending&&state.step>0){state.step--;render(true)}});document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{if(!state.sending){state.step=Number(b.dataset.step);render(true)}}));
next.addEventListener('click',()=>{if(state.sending)return;if(state.step<3&&validStep(state.step)){state.step++;render(true)}else if(state.step===3)send()});document.querySelector('#invitationForm').addEventListener('submit',e=>e.preventDefault());
async function send(){if(![0,1,2].every(validStep)||state.sending||state.sent)return;state.sending=true;next.disabled=true;back.disabled=true;document.querySelectorAll('[data-step]').forEach(b=>b.disabled=true);next.textContent='Отправляем приглашение…';status.textContent='Ещё мгновение';const message=`Алина приняла приглашение на свидание!\nДата: ${dateLabel()}\nКухня: ${state.cuisine}\nВремя: ${state.time} (Москва)`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);
try{const response=await fetch('https://formsubmit.co/ajax/artemcepko69@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},signal:controller.signal,body:JSON.stringify({_subject:'Алина выбрала свидание ♡',name:'Алина',message,'Дата':dateLabel(),'Кухня':state.cuisine,'Время':state.time+' (Москва)',_template:'table',_url:location.href})});const data=await response.json();if(!response.ok||!(data.success===true||data.success==='true'))throw new Error('send-failed');state.sent=true;state.sending=false;render();}
catch(e){state.sending=false;render();status.textContent='Не удалось подтвердить отправку. Попробуй ещё раз или отправь готовое письмо через почту.';document.querySelector('#fallback').hidden=false;document.querySelector('#emailFallback').href='mailto:artemcepko69@gmail.com?subject='+encodeURIComponent('Наше свидание ♡')+'&body='+encodeURIComponent(message);next.innerHTML='Попробовать ещё раз <span>↗</span>';}
finally{clearTimeout(timeout);back.disabled=false}}
render();
